apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "echoupstream.fullname" . }}
data:
  echo.yaml: |-
    {{- with .Values.log }}
    log:
    {{- toYaml . | nindent 5 }}
    {{- end }}
    {{- with .Values.config }}
    config:
    {{- toYaml . | nindent 5 }}
    {{- end }}
    {{- with .Values.application }}
    application:
    {{- toYaml . | nindent 5 }}
    {{- end }}